export const CHECK_JWT_TOKEN_STARTED = 'CHECK_JWT_TOKEN_STARTED';
export const CHECK_JWT_TOKEN_SUCCESS = 'CHECK_JWT_TOKEN_SUCCESS';
export const CHECK_JWT_TOKEN_ERROR = 'CHECK_JWT_TOKEN_ERROR';

export const AUTHORIZATION_STARTED = 'AUTHORIZATION_STARTED';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';

export const LOAD_API_KEY_STARTED = 'LOAD_API_KEY_STARTED';
export const LOAD_API_KEY_SUCCESS = 'LOAD_API_KEY_SUCCESS';
export const LOAD_API_KEY_ERROR = 'LOAD_API_KEY_FAILURE';

export const CREATE_API_KEY_STARTED = 'CREATE_API_KEY_STARTED';
export const CREATE_API_KEY_SUCCESS = 'CREATE_API_KEY_SUCCESS';
export const CREATE_API_KEY_ERROR = 'CREATE_API_KEY_ERROR';

export const DELETE_API_KEY_STARTED = 'DELETE_API_KEY_STARTED';
export const DELETE_API_KEY_SUCCESS = 'DELETE_API_KEY_SUCCESS';
export const DELETE_API_KEY_ERROR = 'DELETE_API_KEY_ERROR';
